### PR TITLE
Simple Calculator

### PR DESCRIPTION
**Pull request by Phildeoner**
-Create UI for calculator using html and css
-Create performEvent Function to perform event on click
-Create performOperation Function to Perform operation

### CODE REVIEW

**Comment by zizoh** [comment]
Great work!  Please consider adding a screenshot of the app.

**Review by DanSam5K — CHANGES_REQUESTED** [review]
## Hi @Phildeoner, ♻️Changes required♻️

### Highlights 🥇 
✔️ Good job! amazing UI design and implementation.
✔️ Great, behind the scene our robot perform our basic arithmetic with ease.

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
 
You can also consider:
- How about getting our screen to capture and display the whole operation for our user before the final result is displayed, what do you think? e.g operation```1+2``` then when press```=``` result ```3``` screen display operation and result.
- I am curious to learn, about the technologies used to accomplish this task, how about including them to your README, what you think? 😉  

- [_Optional_] I clone the branch, to test on my machine, it was great experience testing the app, how about adding procedure for anyone who would like to test, also consider the comment by @zizoh. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by Phildeoner** [comment]
Thank you so much Sirs for your reviews, I really apologize for my late response due to some technical issues, I will implement all corrections and suggestions immediately. Thank you

**Comment by antoHero** [comment]
I cloned the project and all I can say is nice work 👏👏👏 @Phildeoner. Following the suggestions of @zizoh and @DanSam5K will make this repo super.

**Comment by Phildeoner** [comment]
Thank you sir

**Pull request merged**
